/* Filishin LTD — content data (projects, competences, clients, awards, news, charity, licences).
   Sourced from the Filishin archive. Loaded before app.js. */
var SECT={education:"Education",public:"Public",commercial:"Commercial",hospitality:"Hospitality",residential:"Residential","mixed-use":"Mixed-use"};
/* [cat, image, title, featured, location, address, years, overview, technical] — from Filishin project archive */
var RAW=[
 ["education","assets/media/projects/uwc-dilijan/user-cover.jpg","United World College Dilijan",1,"Dilijan","—","2013–2015","A landmark international campus — the Dilijan International School — set into the forested hills of Dilijan.","Multi-building campus (academic, residential and sports facilities) in reinforced concrete, delivered to international accreditation standards on a demanding mountain site."],
 ["public","assets/media/projects/presidential-palace/user-cover.jpg","Presidential Palace",1,"Yerevan","26 Baghramyan Avenue","2008–2010","Construction of the new building of the Presidential Residence on Baghramyan Avenue.","New-build state residence — reinforced-concrete structure with premium stone and interior finishing, executed under state-level security and quality control."],
 ["public","assets/media/projects/presidential-summer-residence/user-cover.jpg","Presidential summer residence, Sevan",1,"Lake Sevan","Lake Sevan shore","2008–2010","A state summer residence on the shore of Lake Sevan.","Prestige residence engineered for the lakeside climate, with premium finishes and landscaped grounds."],
 ["commercial","assets/media/projects/aquatus-showroom/user-cover.png","AQUATUS showroom of saunas & Swimming Pools",0,"Yerevan","23/53 Davit Anhaght Street","2010–2012","Showroom for the AQUATUS sauna and swimming-pool brand.","Commercial showroom construction and fit-out with specialised wet-area and display installations."],
 ["commercial","assets/media/projects/anelik-bank/user-cover.jpg","Anelik Bank",0,"Yerevan","13 Vardanants Street","2010–2011","Reconstruction of the Anelik Bank building on Vardanants Street.","Reconstruction and fit-out to banking security, MEP and finishing standards, on an operating city-centre site."],
 ["hospitality","assets/media/projects/villa-rest-parz-lich/01.jpg","Villa Rest, Parz lich",1,"Dilijan Region","Parz Lich","—","A leisure and hospitality development beside Parz Lich (Clear Lake).","Resort construction integrated with its natural setting, built with Filishin-produced concrete and aggregate."],
 ["commercial","assets/media/projects/ingo-armenia/cover.jpg","INGO ARMENIA",0,"Yerevan","—","—","Facility for the INGO Armenia insurance company.","Commercial office construction and fit-out delivered to corporate standards."],
 ["education","assets/media/projects/chess-school-armavir/cover.jpg","Chess school, Armavir city",0,"Armavir","—","—","A dedicated chess school for the city of Armavir.","Public educational building — reinforced-concrete construction with teaching and competition halls."],
 ["hospitality","assets/media/projects/restaurant-complex-dilijan/cover.jpg","Restaurant complex, Dilijan city",0,"Dilijan","—","—","A restaurant complex in Dilijan.","Hospitality construction with kitchen, dining and service installations."],
 ["mixed-use","assets/media/projects/multipurpose-building-dilijan/cover.jpg","Multipurpose Building in the Dilijan city",0,"Dilijan","Getapnya 2 Street","—","A multipurpose building on Getapnya Street, Dilijan.","Mixed-use monolithic structure combining commercial and public functions."],
 ["residential","assets/media/projects/private-residence-dzoraghbyur/cover.jpg","Private Residence, Dzoraghbyur",0,"Dzoraghbyur","—","—","A private residence in Dzoraghbyur.","Bespoke private home — monolithic reinforced-concrete build with turnkey finishing."],
 ["mixed-use","assets/media/projects/dzorap-70-3/user-cover.jpg","Dzorap 70/3",0,"Yerevan","Dzorap 70/3 & 70/2","2013–2015","Residential buildings at Dzorap 70/3 and 70/2, Yerevan.","Multi-apartment monolithic reinforced-concrete buildings with integrated public-use ground floors."],
 ["residential","assets/media/projects/private-residence-ii-dzoraghbyur/cover.jpg","Private Residence 2, Dzoraghbyur",0,"Dzoraghbyur","—","—","A second private residence in Dzoraghbyur.","Bespoke private home — monolithic reinforced-concrete build with turnkey finishing."],
 ["residential","assets/media/projects/barekamutyun-residential-complex/cover.jpg","Barekamutyun Residential Complex",0,"Yerevan","Barekamutyun district","—","A multi-apartment residential complex in the Barekamutyun district.","Monolithic reinforced-concrete residential complex with turnkey apartments."],
 ["hospitality","assets/media/projects/hotel-complex-dilijan/cover.jpg","Hotel complex, Dilijan city",0,"Dilijan","—","—","A hotel complex in Dilijan.","Hospitality construction with guest rooms and public areas, built for the resort climate."],
 ["commercial","assets/media/projects/yans-music-hall/user-cover.jpg","Yans Music Hall",0,"Yerevan","76 Teryan Street","2010–2012","The Yans Music Hall music club and restaurant on Teryan Street.","Entertainment venue construction and fit-out with acoustic, stage and hospitality installations."],
 ["hospitality","assets/media/projects/hrazdan-hotel-complex/cover.jpg","Hrazdan Hotel Complex",0,"Hrazdan","—","—","Extension and capital renovation of the Hrazdan hotel complex.","Vertical extension (an additional floor) and capital renovation of an operating hotel — structural strengthening with full refurbishment."],
 ["residential","assets/media/projects/yerznkyan-54-1-reconstruction/cover.jpg","Reconstruction of Residential Building at 54/1 Yerznkyan St.",0,"Yerevan","54/1 Yerznkyan Street","—","Reconstruction of the residential building at 54/1 Yerznkyan Street.","Structural reconstruction and refurbishment of an existing residential building."],
 ["residential","assets/media/projects/mori-plaza-renovation/cover.jpg","Renovation of Apartments in Mori Plaza Residential Complex, Tsaghkadzor",0,"Tsaghkadzor","Mori Plaza","—","Renovation of apartments in the Mori Plaza residential complex, Tsaghkadzor.","Interior renovation and turnkey finishing of resort apartments."],
 ["public","assets/media/projects/syunik-regional-customs-house/01.jpg","RA Ministry of Finance, Syunik Regional Customs House",0,"Syunik","—","—","Regional customs house for the RA Ministry of Finance in Syunik.","Institutional facility engineered for operational security and regional service delivery."],
 ["commercial","assets/media/projects/erebuni-administrative-business-complex/02.jpg","Administrative & Business Complex near Erebuni Hotel",0,"Yerevan","Mher Mkrtchyan / Adamyan Streets","—","An administrative and business complex adjacent to the Erebuni Hotel.","Mixed commercial and office complex — reinforced-concrete structure with a contemporary façade."],
 ["education","assets/media/projects/spitak-kindergarten/cover.jpg","Spitak Kindergarten",0,"Spitak","—","—","A kindergarten for the town of Spitak.","Public pre-school building — seismic-aware reinforced-concrete construction in a high-seismic zone."],
 ["public","assets/media/projects/vanadzor-medical-center/user-cover.jpg","Vanadzor Medical Center",1,"Vanadzor","—","2014–2018","A medical centre serving the Lori region from Vanadzor.","Healthcare facility built to medical-grade MEP and hygiene standards; construction reviewed at government level."],
 ["public","assets/media/projects/administrative-building/cover.jpg","THT Administrative Building",0,"Kapan","20a R. Minasyan Street","—","An administrative building on R. Minasyan Street, Kapan.","Administrative building — reinforced-concrete construction with office fit-out."],
 ["mixed-use","assets/media/projects/zigzag-charents-24/user-cover.jpg","Residential and Public Building with Zigzag Showroom",0,"Yerevan","24 Charents Street","2005","A residential and public building incorporating the Zigzag showroom on Charents Street.","Mixed-use monolithic building combining apartments with a ground-floor retail showroom."],
 ["residential","assets/media/projects/antarayin-131-residential-complex/user-cover.png","Residential Complex, 131 Antarayin Street",0,"Yerevan","131 Antarayin Street","2015–2018","A multi-apartment residential complex at 131 Antarayin Street.","Monolithic reinforced-concrete residential complex with turnkey apartments."],
 ["mixed-use","assets/media/projects/antarayin-111-multipurpose-building/user-cover.jpg","Multipurpose Public Building, 11/1 Antarayin Street",0,"Yerevan","11/1 Antarayin Street","2017–2023","A multipurpose public-use building at 11/1 Antarayin Street.","Mixed-use monolithic structure combining public and commercial functions."],
 ["public","assets/media/projects/sos-sargsyan-theatre/user-cover.jpg","Sos Sargsyan Hamazgayin Theatre",1,"Yerevan","3 Henri Verneuil Street","2018–2021","The building of the Sos Sargsyan Hamazgayin Theatre.","Cultural building — reinforced-concrete structure with auditorium, stage and public foyers."],
 ["commercial","assets/media/projects/sas-complex-halabyan-20-4/user-cover.png","SAS Complex, 20/4 Halabyan Street",0,"Yerevan","20/4 Halabyan Street","2020–2021","A public-use SAS retail complex on Halabyan Street.","Retail complex construction and fit-out with supermarket and commercial units."],
 ["hospitality","assets/media/projects/hard-rock-cafe/user-cover.jpg","Hard Rock Cafe Yerevan",0,"Yerevan","3/1 Pushkin Street","2021–2022","Construction of the Hard Rock Cafe global-chain restaurant on Pushkin Street.","Ground-up construction and international-franchise fit-out to Hard Rock brand specification."],
 ["commercial","assets/media/projects/sas-reconstruction-arshakunyats-11-1/user-cover.jpg","SAS Complex Reconstruction, 11/1 Arshakunyats Avenue",0,"Yerevan","11/1 Arshakunyats Avenue","2022–2023","Reconstruction of the SAS public-use facility on Arshakunyats Avenue.","Reconstruction and fit-out of an existing retail facility, delivered on an operating site."]
];
var PROJECTS=RAW.map(function(r,i){return {code:"FL-"+("0"+(i+1)).slice(-2),sect:SECT[r[0]],img:r[1],t:r[2],feat:!!r[3],loc:r[4],addr:r[5],yr:r[6],ov:r[7],tech:r[8]};});

var COMPETENCES=[
 {i:"C-01",t:"Public &amp; Institutional",cimg:"assets/media/projects/sos-sargsyan-theatre/user-cover.jpg",d:"Government, civic and cultural buildings delivered to the highest scrutiny — from ministries and customs houses to presidential residences and theatres.",long:"Public work is where Filishin's reputation was built. We have delivered buildings that carry national weight — the Presidential Palace and the presidential summer residence at Lake Sevan, the Syunik Regional Customs House for the Ministry of Finance, the Sos Sargsyan Hamazgayin Theatre and the Vanadzor Medical Center. Each was built under the security, documentation and quality control that state and civic clients demand, and each depended on a contractor the authorities could trust on a sensitive, high-profile site.",tags:["Ministries","Civic","Cultural","Healthcare"],list:["Government &amp; administrative","Presidential facilities","Theatres &amp; culture","Medical centres"]},
 {i:"C-02",t:"Education",cimg:"assets/media/projects/uwc-dilijan/user-cover.jpg",d:"Campuses, schools and kindergartens engineered for a generation — including the internationally accredited UWC Dilijan.",long:"From the international campus of United World College Dilijan to the Chess School in Armavir and the Spitak Kindergarten, we build places designed to serve generation after generation of students. Educational projects pair demanding safety and accessibility requirements with durable, low-maintenance construction — and, in a seismic country, with structures engineered above all to protect the children and staff inside them.",tags:["Campuses","Schools","Kindergartens"],list:["International campuses","Schools &amp; colleges","Kindergartens","Sports &amp; halls"]},
 {i:"C-03",t:"Commercial &amp; Financial",cimg:"assets/media/projects/anelik-bank/user-cover.jpg",d:"Banking, retail, office and showroom developments — from Anelik Bank to the SAS and Zigzag complexes.",long:"We deliver the buildings Armenian business runs on — the reconstruction of Anelik Bank, the offices of INGO Armenia, the SAS retail complexes, the AQUATUS showroom and the Erebuni business complex. Commercial work is governed by the calendar: owning our materials supply lets us protect tight fit-out and opening dates while meeting the security, services and finishing standards that banking and retail brands expect.",tags:["Banking","Retail","Office","Showrooms"],list:["Bank branches &amp; HQ","Retail &amp; showrooms","Business complexes","Fit-out &amp; renovation"]},
 {i:"C-04",t:"Hospitality &amp; Leisure",cimg:"assets/media/projects/hrazdan-hotel-complex/cover.jpg",d:"Hotels, restaurants and resort developments across Armenia's most scenic regions — Dilijan, Hrazdan, Parz Lich.",long:"In Armenia's most scenic regions — Dilijan, Hrazdan, Tsaghkadzor and Parz Lich — we have built hotels, resorts and restaurants, along with the Hard Rock Cafe in central Yerevan. Hospitality is about experience as much as structure: buildings that sit naturally in their landscape, finished to a standard guests notice, and delivered without disrupting a business that has to keep its doors open.",tags:["Hotels","Resorts","Restaurants"],list:["Resort hotels","Restaurants &amp; cafes","Leisure complexes","Villas &amp; lodges"]},
 {i:"C-05",t:"Residential &amp; Mixed-use",cimg:"assets/media/projects/barekamutyun-residential-complex/cover.jpg",d:"Private residences through to full residential and mixed-use complexes — built with materials we produce ourselves.",long:"Filishin builds homes at every scale — private residences in Dzoraghbyur, multi-apartment complexes such as Barekamutyun and 131 Antarayin Street, and mixed-use buildings that place apartments above shops and public space. Our monolithic reinforced-concrete method, poured with our own concrete, gives residents solid, seismic-aware buildings and gives developers cost and programme they can plan around.",tags:["Complexes","Villas","Mixed-use","Turnkey"],list:["Apartment complexes","Private residences","Mixed-use blocks","Reconstruction"]},
 {i:"C-06",t:"Materials &amp; Production",cimg:"assets/media/manufacturing-base/balahovit-concrete-production/01.jpg",d:"Concrete, asphalt and graded aggregate produced in-house at our Dilijan and Balahovit bases — the backbone of every project.",long:"Few Armenian builders own what goes into their buildings. Filishin runs a crushing-and-washing line in the Dilijan region and a concrete plant in Balahovit, and produces asphalt and graded aggregate. Controlling the chain from quarry to pour means consistent, tested material, shorter haulage and schedules that never stall waiting on a third-party supplier — the single biggest reason we can commit to demanding deadlines.",tags:["Concrete","Asphalt","Aggregate"],list:["Ready-mix concrete","Asphalt production","Crushing &amp; washing","Supply to third parties"]}
];
var LICENCES=[
 {img:"assets/media/licenses/01.jpg",t:"Construction Licence",n:"Legacy archive scan"},
 {img:"assets/media/licenses/02.jpg",t:"Licence No. 13878",n:"Original archive scan"},
 {img:"assets/media/licenses/03.jpg",t:"Licence No. 13879",n:"Original archive scan"},
 {img:"assets/media/licenses/04.jpg",t:"Licence No. 12000",n:"Original archive scan"}
];

var CLIENTS=[
 ["Office of the President","State"],["RA Ministry of Finance","Government"],["Tashir Group","Development"],["Armbusinessbank","Financial"],["Anelik Bank","Financial"],
 ["Renco Armenia","Industry"],["Gradshin Invest","Development"],["Lada Fora / Ford","Automotive"],["UWC Dilijan","Education"],["City of Dilijan","Municipal"]
];

var AWARDS=[
 ["2014","Winner — Pan-National Trust Awards 2014","Recognition"],
 ["2016","Prime Minister's Commemorative Medal — Suren Hakobyan","Honour"],
 ["2011","Independent financial audit — N-AUDIT LLC (FY 2010)","Governance"],
 ["Ongoing","Construction &amp; professional licences on record","Compliance"]
];

var NEWS=[
 {d:"2014",cat:"Company",t:"Filishin wins at the Pan-National Trust Awards 2014",img:"assets/media/projects/uwc-dilijan/user-cover.jpg"},
 {d:"13.10.2014",cat:"Projects",t:"Filishin's contribution to the construction of UWC Dilijan",img:"assets/media/projects/uwc-dilijan/01.jpg"},
 {d:"03.12.2014",cat:"Community",t:"Bridge of Hope opens in Dilijan",img:"assets/media/projects/villa-rest-parz-lich/01.jpg"},
 {d:"20.10.2015",cat:"Company",t:"Memorial plaque to honored builder Edik Hakobyan unveiled in Yerevan",img:"assets/media/projects/presidential-palace/user-cover.jpg"},
 {d:"13.08.2016",cat:"Projects",t:"Prime Minister visits the Vanadzor Technology Center",img:"assets/media/projects/vanadzor-medical-center/user-cover.jpg"},
 {d:"12.08.2016",cat:"Company",t:"Director Suren Hakobyan awarded the Prime Minister's Commemorative Medal",img:"assets/media/projects/sos-sargsyan-theatre/user-cover.jpg"},
 {d:"12.04.2017",cat:"Industry",t:"Consultation between the Head of Government and developers",img:"assets/media/projects/erebuni-administrative-business-complex/02.jpg"},
 {d:"19.03.2017",cat:"Projects",t:"Prime Minister reviews construction of the Vanadzor hospital complex",img:"assets/media/projects/vanadzor-medical-center/user-cover.jpg"},
 {d:"20.12.2017",cat:"Industry",t:"Delegation led by the Chairman of the State Urban Development Committee",img:"assets/media/projects/administrative-building/cover.jpg"},
 {d:"22.02.2018",cat:"Industry",t:"Armenia and Russia to cooperate in the construction sector",img:"assets/media/projects/antarayin-131-residential-complex/user-cover.png"}
];

var CHARITY=[
 {tg:"Education / Community",t:"Charitable investment in Dzerzhinsky School No. 20 &amp; Haghartsin Secondary School",d:"Director Suren Hakobyan supported both schools through direct charitable investment in their facilities."},
 {tg:"Education / Community",t:"Haghartsin students visit Dalma Garden Mall with Filishin's support",d:"Graduating students of Haghartsin Secondary School visited Yerevan on a trip funded by the company."},
 {tg:"Children / Community",t:"A celebration for the children of Bridge of Hope in Dilijan",d:"A Filishin charity initiative for the children supported by the Bridge of Hope organization in Dilijan."}
];
